const list = [
"Andorra,ad,Europe,1",
"Angola,ao,Africa,5",
"Antigua & Barbuda,ag,North America,1",
"Armenia,am,Asia,4",
"Austria,at,Europe,1",
"Azerbaijan,az,Asia,2",
"The Bahamas,bs,North America,5",
"Bahrain,bh,Asia,2",
"Bangladesh,bd,Asia,6",
"Barbados,bb,North America,1",
"Belarus,by,Europe,2",
"Belgium,be,Europe,1",
"Belize,bz,North America,5",
"Benin,bj,Africa,3",
"Bhutan,bt,Asia,2",
"Bolivia,bo,South America,6",
"Bosnia & Herzegovina,ba,Europe,2",
"Botswana,bw,Africa,6",
"Brunei,bn,Asia,5",
"Bulgaria,bg,Europe,2",
"Burkina Faso,bf,Africa,6",
"Burundi,bi,Africa,5",
"Cape Verde,cv,Africa,6",
"Cambodia,kh,Asia,4",
"Cameroon,cm,Africa,3",
"Central African Republic,cf,Africa,6",
"Chad,td,Africa,1",
"Colombia,co,South America,3",
"Comoros,km,Africa,1",
"Republic of the Congo,cg,Africa,1",
"Democratic Republic of the Congo,cd,Africa,2",
"Costa Rica,cr,North America,6",
"Ivory Coast,ci,Africa,3",
"Croatia,hr,Europe,1",
"Cuba,cu,North America,4",
"Cyprus,cy,Asia,2",
"Czechia,cz,Europe,6",
"Denmark,dk,Europe,1",
"Djibouti,dj,Africa,3",
"Dominica,dm,North America,1",
"Dominican Republic,do,North America,3",
"Ecuador,ec,South America,5",
"Egypt,eg,Africa,1",
"El Salvador,sv,North America,2",
"Equatorial Guinea,gq,Africa,1",
"Eritrea,er,Africa,1",
"Estonia,ee,Europe,5",
"Eswatini,sz,Africa,2",
"Ethiopia,et,Africa,6",
"Fiji,fj,Oceania,4",
"Finland,fi,Europe,2",
"France,fr,Europe,5",
"Gabon,ga,Africa,4",
"Gambia,gm,Africa,2",
"Georgia,ge,Asia,6",
"Germany,de,Europe,2",
"Ghana,gh,Africa,1",
"Greece,gr,Europe,6",
"Grenada,gd,North America,3",
"Guatemala,gt,North America,3",
"Guinea,gn,Africa,6",
"Guinea-Bissau,gw,Africa,1",
"Guyana,gy,South America,2",
"Haiti,ht,North America,1",
"Vatican City,va,Europe,6",
"Honduras,hn,North America,1",
"Hungary,hu,Europe,3",
"Iceland,is,Europe,2",
"Indonesia,id,Asia,6",
"Iran,ir,Asia,5",
"Iraq,iq,Asia,2",
"Ireland,ie,Europe,6",
"Israel,il,Asia,2",
"Italy,it,Europe,2",
"Jamaica,jm,North America,2",
"Japan,jp,Asia,1",
"Jordan,jo,Asia,4",
"Kenya,ke,Africa,1",
"Kiribati,ki,Oceania,2",
"Kosovo,xk,Europe,1",
"North Korea,kp,Asia,2",
"South Korea,kr,Asia,4",
"Kuwait,kw,Asia,1",
"Kyrgyzstan,kg,Asia,3",
"Laos,la,Asia,2",
"Latvia,lv,Europe,1",
"Lebanon,lb,Asia,6",
"Lesotho,ls,Africa,3",
"Liberia,lr,Africa,2",
"Libya,ly,Africa,6",
"Liechtenstein,li,Europe,6",
"Lithuania,lt,Europe,6",
"Luxembourg,lu,Europe,4",
"Madagascar,mg,Africa,3",
"Malawi,mw,Africaa,2",
"Malaysia,my,Asia,2",
"Maldives,mv,Asia,1",
"Mali,ml,Africa,4",
"Malta,mt,Europe,3",
"Marshall Islands,mh,Oceania,4",
"Mauritania,mr,Africa,2",
"Mauritius,mu,Africa,2",
"Federated States of Micronesia,fm,Oceania,5",
"Moldova,md,Europe,1",
"Monaco,mc,Europe,3",
"Montenegro,me,Europe,3",
"Morocco,ma,Africa,4",
"Mozambique,mz,Africa,5",
"Myanmar,mm,Asia,1",
"Namibia,na,Africa,3",
"Nauru,nr,Oceania,5",
"Nepal,np,Asia,1",
"Netherlands,nl,Europe,3",
"New Zealand,nz,Oceania,3",
"Nicaragua,ni,North America,4",
"Niger,ne,Africa,2",
"Nigeria,ng,Africa,6",
"North Macedonia,mk,Europe,4",
"Norway,no,Europe,6",
"Oman,om,Asia,6",
"Pakistan,pk,Asia,2",
"Palau,pw,Oceania,3",
"Palestine,ps,Asia,5",
"Panama,pa,North America,1",
"Papua New Guinea,pg,Oceania,1",
"Paraguay,py,South America,3",
"Peru,pe,South America,2",
"The Philippines,ph,Asia,1",
"Poland,pl,Europe,1",
"Portugal,pt,Europe,3",
"Qatar,qa,Asia,1",
"Romania,ro,Europe,5",
"Rwanda,rw,Africa,1",
"St. Kitts & Nevis,kn,North America,2",
"St. Lucia,lc,North America,3",
"St. Vincent & the Grenadines,vc,North America,2",
"Samoa,ws,Oceania,2",
"San Marino,sm,Europe,3",
"Sao Tome and Principe,st,Africa,3",
"Saudi Arabia,sa,Asia,3",
"Senegal,sn,Africa,3",
"Serbia,rs,Europe,6",
"Seychelles,sc,Africa,5",
"Sierra Leone,sl,Africa,1",
"Singapore,sg,Asia,1",
"Slovakia,sk,Europe,4",
"Slovenia,si,Europe,6",
"Solomon Islands,sb,Oceania,3",
"Somalia,so,Africa,2",
"South Africa,za,Africa,1",
"South Sudan,ss,Africa,4",
"Spain,es,Europe,2",
"Sri Lanka,lk,Asia,2",
"Sudan,sd,Africa,2",
"Suriname,sr,South America,4",
"Sweden,se,Europe,3",
"Switzerland,ch,Europe,3",
"Syria,sy,Asia,3",
"Taiwan,tw,Asia,6",
"Tajikistan,tj,Asia,4",
"Tanzania,tz,Africa,3",
"Thailand,th,Asia,6",
"Timor-Leste,tl,Asia,3",
"Togo,tg,Africa,2",
"Tonga,to,Oceania,1",
"Trinidad & Tobago,tt,North America,1",
"Tunisia,tn,Africa,1",
"Turkey,tr,Asia,1",
"Turkmenistan,tm,Asia,3",
"Tuvalu,tv,Oceania,3",
"Uganda,ug,Africa,5",
"Ukraine,ua,Europe,6",
"United Arab Emirates,ae,Asia,2",
"United Kingdom,gb,Europe,3",
"Uruguay,uy,South America,4",
"Uzbekistan,uz,Asia,6",
"Vanuatu,vu,Oceania,2",
"Venezuela,ve,South America,6",
"Vietnam,vn,Asia,3",
"Yemen,ye,Asia,2",
"Zambia,zm,Africa,1",
"Zimbabwe,zw,Africa,4",]
let listInd = 0

function automateCountryLabels() {
    svg.contentDocument.addEventListener("click", function(event) {
        const c = list[listInd++].split(",")
        const country = c[0]
        const code = c[1]

        const point = getPoint(event)
        const x = Math.round(point.x) + 50
        const y = Math.round(point.y) + 20

        const str = "<text x=\"" + x + "\" y=\"" + y + "\" class=\"countrylabel\" id=\"" + code + "-label\">" + country + "</text>"
        console.log(str)
    })
    
}

function getPoint(event) {
    //convert screen coordinates to SVG coordinates
    let point = svgTag.createSVGPoint()
    point.x = event.clientX
    point.y = event.clientY
    point = point.matrixTransform(svgTag.getScreenCTM().inverse());
    return point
}